version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
jobs:
  supply_creds:
    executor: terraform/default
    steps:
      - run: echo "$MY_CREDS_FILE" | base64 -d > credentials.json; echo "$GCS_CREDS_FILE" | base64 -d > gcs.json; echo "$INSTANCE_CREDS_FILE" | base64 -d > instance_creds.json
      - persist_to_workspace:
              root: .
              paths:
                - .
  terraform_destroy:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run: terraform destroy -auto-approve
      - persist_to_workspace:
              root: .
              paths:
                - .
workflows:
  deploy_infrastructure:
    jobs:
      - supply_creds
      - terraform/init:
          attach-workspace: true
          checkout: true
          context: terraform
          requires:
            - supply_creds
      - terraform/validate:
          attach-workspace: true
          checkout: true
          context: terraform
          requires:
            - terraform/init
      - terraform/plan:
          attach-workspace: true
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - hold-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - hold-apply
      - hold-destroy:
          type: approval
          requires:
            - terraform/apply
      - terraform_destroy:
          requires:
            - hold-destroy
      