version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
jobs:
  supply_creds:
    executor: terraform/default
    steps:
      - run: echo "$MY_CREDS_FILE" | base64 -d > credentials.json
      - persist_to_workspace:
              root: .
              paths:
                - .
  delete_stuff:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run: ls -la /; pwd; which terraform
      - persist_to_workspace:
              root: .
              paths:
                - .
workflows:
  deploy_infrastructure:
    jobs:
      - supply_creds
      - terraform/init:
          attach-workspace: true
          checkout: true
          context: terraform
          requires:
            - supply_creds
      - terraform/validate:
          attach-workspace: true
          checkout: true
          context: terraform
          requires:
            - terraform/init
      - terraform/plan:
          attach-workspace: true
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - delete_stuff
          requires:
            - terraform/plan
      # - terraform/destroy:
      #     attach-workspace: true
      #     context: terraform
      #     requires:
      #       - delete_stuff         